version: "3.8"
services:
    database:
      image: postgres:${POSTGRES_VERSION-13}
      container_name: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - database-data:/var/lib/postgresql/data
      ports:
        - 5432:5432

    agent-order-service:
      build: 
        context: ./agent-order
        dockerfile: Dockerfile
        target: agentOrderServiceTest
      command:  bash -c "apt-get update && apt-get install -y netcat && ./wait.sh -w \"database:5432\" --command \"mvn -B verify -P${STAGE} sonar:sonar -P${STAGE} -Dsonar.projectKey=${SONAR_PROJ_KEY_ORDER_SVC} -Dsonar.organization=${SONARCLOUD_ORGANIZATION} -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN_ORDER} \""
      container_name: agent-order
      ports:
        - 8080:8080
      environment:
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_DOMAIN: ${DATABASE_DOMAIN}
        DATABASE_SCHEMA: ${DATABASE_SCHEMA}
        STAGE: ${STAGE}
        SONAR_TOKEN: ${SONAR_TOKEN_ORDER}
      depends_on:
        - database


volumes:
  database-data:
    name: server-database
