version: "3.8"
services:
    agent-order-service:
      build: 
        context: .
        dockerfile: Dockerfile
        target: agentOrderServiceTest
      command: bash -c "mvn -B verify -P${STAGE} sonar:sonar -P${STAGE} -Dsonar.projectKey=${SONAR_PROJ_KEY_ORDER_SVC} -Dsonar.organization=${SONARCLOUD_ORGANIZATION} -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN_ORDER} -Dsonar.branch.name=${BRANCH_NAME} -Dsonar.pullrequest.key=${PULL_KEY} -Dsonar.pullrequest.branch=${PULL_REQUEST_BRANCH} -Dsonar.pullrequest.base=${BASE}"
      container_name: agent-order
      ports:
        - 8080:8080
      environment:
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_DOMAIN: ${DATABASE_DOMAIN}
        DATABASE_SCHEMA: ${DATABASE_SCHEMA}
        STAGE: ${STAGE}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
      depends_on:
        - database
        
    agent-product-service:
      build: 
        context: .
        dockerfile: Dockerfile
        target: agentProductServiceTest
      command:  bash -c "mvn -B verify -P${STAGE} sonar:sonar -P${STAGE} -Dsonar.projectKey=${SONAR_PROJ_KEY_PRODUCT_SVC} -Dsonar.organization=${SONARCLOUD_ORGANIZATION} -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN_PRODUCT} -Dsonar.branch.name=${BRANCH_NAME} -Dsonar.pullrequest.key=${PULL_KEY} -Dsonar.pullrequest.branch=${PULL_REQUEST_BRANCH} -Dsonar.pullrequest.base=${BASE}"
      container_name: agent-product
      ports:
        - 8081:8080
      environment:
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_DOMAIN: ${DATABASE_DOMAIN}
        DATABASE_SCHEMA: ${DATABASE_SCHEMA}
        STAGE: ${STAGE}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
      depends_on:
        - database

    agent-report-service:
      build: 
        context: .
        dockerfile: Dockerfile
        target: agentReportServiceTest
      command:  bash -c "mvn -B verify -P${STAGE} sonar:sonar -P${STAGE} -Dsonar.projectKey=${SONAR_PROJ_KEY_REPORT_SVC} -Dsonar.organization=${SONARCLOUD_ORGANIZATION} -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${SONAR_TOKEN_REPORT} -Dsonar.branch.name=${BRANCH_NAME} -Dsonar.pullrequest.key=${PULL_KEY} -Dsonar.pullrequest.branch=${PULL_REQUEST_BRANCH} -Dsonar.pullrequest.base=${BASE}"
      container_name: agent-report
      ports:
        - 8082:8080
      environment:
        DATABASE_USERNAME: ${DATABASE_USERNAME}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        DATABASE_DOMAIN: ${DATABASE_DOMAIN}
        DATABASE_SCHEMA: ${DATABASE_SCHEMA}
        STAGE: ${STAGE}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
      depends_on:
        - database

    # run unit tests on front-end
    front-end-service:
      build: 
        context: .
        dockerfile: Dockerfile
        target: frontEndTest
      container_name: front-end
      command: bash -c "CI=true npm run test"

volumes:
  database-data:
    name: server-database

