export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";
export const API_CALL_END = "API_CALL_END";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHECK_USER_IS_AGENT_SUCCESS = "CHECK_USER_IS_AGENT_SUCCESS";